name: er_squeeze
description: "Compress videos on your phone to save space without losing quality!"
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path_provider_android: ^2.2.9
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  path: ^1.9.1
  fluttertoast: ^9.0.0
  flutter_foreground_task: ^9.1.0
  ffmpeg_kit_flutter_new: ^3.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  video_player: ^2.9.2

  # NEW: MediaStore-based video access
  photo_manager: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
